#
# embedXcode
# ----------------------------------
# Embedded Computing on Xcode
#
# Copyright © Rei VILO, 2010-2016
# http://embedxcode.weebly.com
# All rights reserved
#
# Last update: Apr 07, 2016 release 4.4.5
#

# ----------------------------------
# DO NOT EDIT THIS FILE.
# ----------------------------------

EMBEDXCODE_RELEASE      = 4.4.5
EMBEDXCODE_DATE         = Apr 07, 2016
EMBEDXCODE_MESSAGE      = Updated support for Intel Edison Yocto and MCU

# ~
EMBEDXCODE_EDITION      = embedXcode+ for mbed
EMBEDXCODE_REFERENCE    = embedXcode+ mbed
EMBEDXCODE_TEMPLATE     = NmiFVEpTZkMqAfrNXJh7pgGKXf6GJLwz
# ~~


# mbed SDK
# ----------------------------------
# BLE requires 92, otherwise 112
#
MBED_SDK_RELEASE        = 112


# Arduino.ORG
# ----------------------------------
#
ARDUINO_ORG_RELEASE     = 1.7.9


# Arduino.CC or Genuino with Boards Manager
# ----------------------------------
#
ARDUINO_CC_RELEASE      = 1.6.8

ARDUINO_AVR_RELEASE     = 1.6.10
AVR_GCC_RELEASE         = 4.8.1-arduino5
AVRDUDE_RELEASE         = 6.0.1-arduino5

# Boards for Arduino.CC 1.6.5 or Genuino
#
ADAFRUIT_AVR_RELEASE    = 1.4.6
ADAFRUIT_SAMD_RELEASE   = 1.0.8

ARDUINO_SAM_RELEASE     = 1.6.7
ARDUINO_SAMD_RELEASE    = 1.6.4
ARM_GCC_RELEASE         = 4.8.3-2014q1
BOSSAC_RELEASE          = 1.6.1-arduino
CMSIS_RELEASE           = 4.0.0-atmel
OPENOCD_RELEASE         = 0.9.0-arduino

CHIPKIT_RELEASE         = 1.1.0
PIC32_GCC_RELEASE       = 4.8.3-pic32gcc
PIC32_PROG_RELEASE      = v1.0.01-pic32gcc

COSA_AVR_RELEASE        = 1.2.0

DIGISTUMP_AVR_RELEASE   = 1.6.7
DIGISTUMP_OAK_RELEASE   = 1.0.1
DIGISTUMP_SAM_RELEASE   = 1.6.5
OAK_ESPTOOLS_RELEASE    = 0.9.1
OAK_MKSPIFFS_RELEASE    = 0.1.2
OAK_OAKCLI_RELEASE      = 1.0.1
OAK_EXTENSA_RELEASE     = 1.20.0-26-gb404fb9-2

ESP8266_RELEASE         = 2.1.0
ESPTOOLS_RELEASE        = 0.4.8
EXTENSA_RELEASE         = 1.20.0-26-gb404fb9-2

INTEL_EDISON_RELEASE    = 1.6.7+1.0
INTEL_GALILEO_RELEASE   = 1.6.7+1.0
INTEL_CURIE_RELEASE     = 1.0.5
INTEL_ARC_RELEASE       = 1.6.4+1.0
INTEL_CORE2_RELEASE     = 1.6.2+1.0
INTEL_I586_RELEASE      = 1.6.2+1.0
INTEL_UPLOAD_RELEASE    = 1.6.2+1.0
INTEL_CURIE_UPLOAD_RELEASE = 1.6.4+1.18

LINKIT_ONE_RELEASE      = 1.1.21
LINKIT_DUO_RELEASE      = 0.1.6

LITTLEROBOTFRIENDS_AVR_RELEASE = 1.6.0

MOTEINO_AVR_RELEASE     = 1.1.0

PANSTAMP_AVR_RELEASE    = 1.5.4
PANSTAMP_MSP_RELEASE    = 1.0.6

REDBEARLAB_DUO_RELEASE  = 0.2.7
DUO_GCC_ARM_RELEASE     = 4.9-2015-q3
REDBEARLAB_AVR_RELEASE  = 1.0.2
REDBEARLAB_NRF_RELEASE  = 1.0.5
NRF_GCC_ARM_RELEASE     = 4.8.3-2014q1

RFDUINO_RELEASE         = 2.3.1
SIMBLEE_RELEASE         = 1.0.2

UDOO_NEO_RELEASE        = 1.6.5
UDOO_GCC_ARM_RELEASE    = 4.9-2014q4-20141203
UDOO_CLIENT_RELEASE     = 1.0
